#!/usr/bin/python3

from sys import argv

def factors(num):
    n = 2
    while num % n != 0:
        n += 1
    return n

with open(argv[1], 'r') as f:
    for x in f:
    #num = int(" ".join(x.split()))
        num = int(x)
        denum = factors(num)
    #print(num, denum)
        print("{}={}*{}".format(num, num//denum, denum))
